### ISSUE TITLE
created incomplete structures

### ISSUE THREAD

**Issue by sby1678** [sby1678/MatBuilder-V1#1]
When I was testing the code with Si-opt.cit and maxMillerIdx=2, following structures are not complete:
Si-opt 0 1 2
Si-opt 0 2 1
Si-opt 1 0 2
Si-opt 1 1 1
Si-opt 1 1 2
Si-opt 1 2 0

I tried to increased both nbulk and nbulk2 to 2*max Miller index, but the problem still exists. The program stops after Si-opt 1 2 0 so I don't know how would it work for higher indices.

**Comment by teoqba** [comment]
Incomplete structures like this means that nbulk2 is too small for given nlayer. For instance if for (111) you will increase nbulk2 to 4, everything will be fine.
