### ISSUE TITLE
MatBuilder stops at Si-opt 1 2 1

### ISSUE THREAD

**Issue by sby1678** [sby1678/MatBuilder-V1#2]
with following error message:
RuntimeWarning: invalid value encountered in double_scalars cosphi = np.dot(self.a, self.b)/(self.norma*self.normb)

I guess what happened was that the denominator is 0.

**Comment by teoqba** [comment]
There was rounding error in the routines to find primitive vectors, that gave rise to this error and prevented the orientation to be created. Fixed in the code
