### ISSUE TITLE
Error on Si-opt 2 2 2

### ISSUE THREAD

**Issue by sby1678** [sby1678/MatBuilder-V1#3]
![capture](https://cloud.githubusercontent.com/assets/8390956/6014203/97ed46ac-ab14-11e4-9550-f25b7447a28f.PNG)

**Comment by teoqba** [comment]
That's remaining stuff from the big code, that for some reasons went crazy when I shrinked the code. I will take care of if.

**Comment by teoqba** [comment]
Fixed. In fact 2 2 2 orientation does not exists. I have added additional check for it. Now the program will not crash upon encountering such situation.
